services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end/monitoramento-trafego
      dockerfile: Dockerfile
    ports:
      - "8080:8080"